### ISSUE TITLE
[BUG] The plugin does not pick up tailwind configs in projects nested within monorepos

### ISSUE THREAD

**Issue by quesabe** [francoismassart/eslint-plugin-tailwindcss#241]
**Describe the bug**
When a frontend project is nested within a monorepo, any linting process run not from the frontend folder does not see the tailwind config. This is especially apparent with _VSCode_ intellisense - the _eslint_ process is run at the project root level, while the tailwind config resides somewhere nested. Since the config is not found the plugin des not pick up any custom colours and other stuff.

**To Reproduce**
Assumed folder structure:
```
/rootProject
├ package.json
├ /frontend
│  ├ .eslintrc.js 
│  ├ package.json
│  ├ tailwind.config.js
```
1. When _eslint_ is run from `rootProject` folder the `tailwind.config.js` **is not** found.
2. When _eslint_ is run from `frontend` folder the `tailwind.config.js` **is** found.
3. _eslint_ process in _VSCode_ is run from `rootProject` and thus does not find the `tailwind.config.js`.

BTW, the _eslint_ config is picked up and the rules from `eslint-plugin-tailwindcss` apply - they just don't use the custom theme and other settings.

**Expected behavior**
_Tailwind_ config is discoverable as long as it is in the same folder with the _eslint_ config.

**Environment (please complete the following information):**
- VSCode@1.77.3
- eslint@8.37.0
- tailwindcss@3.3.2
- eslint-plugin-tailwindcss@3.11.0

**Additional context**
Seems like this code is the reason for the behaviour:
https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/lib/util/customConfig.js#L26

The `path.resolve()` resolves to the `rootProject` folder, while the config is at `rootProject/frontend`.

PS. I can make it work if I open the `frontend` folder in a separate editor window. However it is very inconvenient in a large project.

**Comment by Gomah** [comment]
Do you mind sharing your current `.eslintrc.js` file?

I just fixed a similar issue and this worked for me:

```js
// .eslintrc.js
settings: {
  tailwindcss: {
    config: path.join(__dirname, './tailwind.config.js'),
  },
},
```

**Comment by av-erencelik** [comment]
I can confirm @Gomah 's solution works.

**Comment by quesabe** [comment]
> Do you mind sharing your current `.eslintrc.js` file?
> 
> I just fixed a similar issue and this worked for me:
> 
> ```js
> // .eslintrc.js
> settings: {
>   tailwindcss: {
>     config: path.join(__dirname, './tailwind.config.js'),
>   },
> },
> ```

It's fairly simple:
```json
{
  "env": {
    "browser": true,
    "jest": true,
    "node": false
  },
  "plugins": [
    "tailwindcss"
  ],
  "rules": {
    "tailwindcss/classnames-order": [
      "error"
    ],
    "tailwindcss/enforces-negative-arbitrary-values": [
      "error"
    ],
    "tailwindcss/enforces-shorthand": [
      "error"
    ],
    "tailwindcss/migration-from-tailwind-2": [
      "error"
    ],
    "tailwindcss/no-arbitrary-value": [
      "off"
    ],
    "tailwindcss/no-contradicting-classname": [
      "error"
    ],
    "tailwindcss/no-custom-classname": [
      "error",
    ]
  },
  "settings": {
    "tailwindcss": {
      "callees": [
        "cn"
      ],
      "config": "tailwind-config.js"
    }
  }
}
```

In fact I can't use the workaround, since I use a JSON config.

**Comment by francoismassart** [comment]
@quesabe did [your commit](https://github.com/francoismassart/eslint-plugin-tailwindcss/commit/83ded23d0956dfbc04c1f1891cc77d36fc8807a2) provide a solution for your issue with JSON config ?
@Gomah , @av-erencelik & @quesabe Can we close this issue ? It looks like you found a workaround...

**Comment by quesabe** [comment]
> @quesabe did [your commit](https://github.com/francoismassart/eslint-plugin-tailwindcss/commit/83ded23d0956dfbc04c1f1891cc77d36fc8807a2) provide a solution for your issue with JSON config ?
> @Gomah , @av-erencelik & @quesabe Can we close this issue ? It looks like you found a workaround...

Actually no, the commit does not solve the current issue completely. It helps in my case, where I can get rid of the custom config. But if anybody needs to use a json _eslint_ config, refer to a custom _tailwind_ config, and all this done not in the root folder of a project, then it still won't load the _tailwind_ config properly.

However I'm not sure if it has a solution within the plugin repo - maybe it's a problem with _eslint_ itself.

**Comment by lachieh** [comment]
After doing some digging, it looks like the vscode-eslint extension is not passing the context object is not being passed to the the rules when running from a higher level folder. You can confirm this yourself by being in your root project folder and running `npx eslint ./your-package` where `your-package` is where the eslint and tailwind config files are and it will lint the whole project without issue.

Apparently the solution is the `eslint.workingDirectories` setting in the workspace `.vscode/settings.json`. The following config should fix the problem.
```json
{
  "eslint.workingDirectories": ["./your-package"],
}
```

**Comment by maslennikov** [comment]
@lachieh Your suggested workaround with custom `.vscode/settings.json` wouldn't be practical for teams working on same monorepo, since custom vscode settings do not normally belong to codebase committed to git.

**Comment by lachieh** [comment]
> @lachieh Your suggested workaround with custom `.vscode/settings.json` wouldn't be practical for teams working on same monorepo, since custom vscode settings do not normally belong to codebase committed to git.

@maslennikov I didn't actually say that this file should be committed. I just provided a solution for correctly configuring the eslint extension.

Whether it is practical or not is subjective and committing this file is a team decision. If your team has decided that shared workspace settings should actually not be shared, then perhaps you can find and suggest a different solution instead of just spreading your (unsolicited) opinion.

For example, a common pattern is to add the `.vscode/settings.json` file in `.gitignore` but include shared settings in a `.vscode/settings.default.json` so that developers can copy required settings and customize the settings themselves.

**Comment by jrozbicki** [comment]
[Gomah](https://github.com/Gomah) thanks for the suggestion! Works 🚀

**Comment by nodegin** [comment]
@quesabe Thank you for the solution! It was working for me

**Comment by yossydev** [comment]
I was also facing this problem in a Monorepo environment using Turborepo, but I tried the contents of https://github.com/microsoft/vscode-eslint/issues/1706#issuecomment-1785746444 I tried the contents of  and it worked fine.

**Comment by joshuajaco** [comment]
I think the only proper way to solve this is by searching for the config based on the location of the file that is being linted.
Similar to what typescript-eslint is doing now, see: https://typescript-eslint.io/blog/parser-options-project-true/#introducing-true

**Comment by ImamAlfariziSyahputra** [comment]
> Do you mind sharing your current `.eslintrc.js` file?
> 
> I just fixed a similar issue and this worked for me:
> 
> ```js
> // .eslintrc.js
> settings: {
>   tailwindcss: {
>     config: path.join(__dirname, './tailwind.config.js'),
>   },
> },
> ```

it works in monorepo thank you soo much!!

**Comment by DigitalNaut** [comment]
> Do you mind sharing your current `.eslintrc.js` file?
> 
> I just fixed a similar issue and this worked for me:
> 
> ```js
> // .eslintrc.js
> settings: {
>   tailwindcss: {
>     config: path.join(__dirname, './tailwind.config.js'),
>   },
> },
> ```

This works but I'm not using a monorepo. I'm using the base Vite template from `pnpm create vite`.

**Comment by jtwozniak** [comment]
After trying some suggestions I found that vs code eslint run can be detected by checking if the config file exist:
`const isVsEslintRun = fs.existsSync("./apps/web/tailwind.config.ts");`

Then in specific package setup after adding below it works for VsEslint and when running script command 
```
{
    files: ["apps/web/**/*.{ts,tsx,mts,cts,js,jsx}"],
    settings: {
      tailwindcss: {
        config: isVsEslintRun ? "./apps/web/tailwind.config.ts" : undefined,
      },
    },
  },

```

**Comment by colinscz** [comment]
Just for people landing here who have a *.json eslint configuration and are working with a monorepo tool like Nx and wonder how to get this working. 

In my case I resolved it by referencing the tailwind-preset library in the monorepo top-level file _.eslintrc.json_. 
I still have an issue with the configuration of the IntelliJ EsLint plugin but for the command execution it looks fine.
This section in my top-level file looks like this:

```
{
  "root": true,
  "ignorePatterns": ["**/*"],
  "plugins": ["@nx"],
  "settings": {
    "tailwindcss": {
      "config": "./libs/tailwind-preset/tailwind.config.js"
    }
  },
...
}
```

**Comment by francoismassart** [comment]
Closing this issue, cleaning up before release of v4.
